name: Deploy

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - uses: actions/checkout@v7
            - name: env 4 docker compose
              run: |
                echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env
                echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
                echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> .env

            - name: Deploy
              run: |
                docker compose pull
                docker compose up -d
            